// Generated by Selenium IDE
package org.ual.cnsa.agu528;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;

public class EditarperfilCCTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		//System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
		// System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
		// driver = new ChromeDriver();
		FirefoxOptions firefoxOptions = new FirefoxOptions();
		firefoxOptions.setHeadless(true);
		//firefoxOptions.addArguments("--headless");
		firefoxOptions.addArguments("--width=426");
		firefoxOptions.addArguments("--height=728");
		
		//firefoxOptions.addArguments("window-size=1440,900");
		//driver.manage().window().setSize(new Dimension(1080, 824));
		driver = new FirefoxDriver(firefoxOptions);
		driver.manage().window().maximize();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void editarperfilCC() {
		// Test name: Editar el usuario logueado(CC)
		// Step # | name | target | value
		// 1 | open | / |
		driver.get("http://webapps.alejandrogacles.tech:8080//");
		// 2 | setWindowSize | 697x728 |
		driver.manage().window().setSize(new Dimension(426, 728));
		// 3 | click | linkText=Log in |
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Log in")));
		}
		try {
	        Thread.sleep(1000);
	      } catch (InterruptedException e) {
	        e.printStackTrace();
	      }
		driver.findElement(By.linkText("Log in")).click();
		// 4 | click | css=.form-group:nth-child(1) > .form-control |
		//driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
		// 5 | type | css=.form-group:nth-child(1) > .form-control | user1@ual.es
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".form-group:nth-child(1) > .form-control")));
		}
		try {
	        Thread.sleep(1000);
	      } catch (InterruptedException e) {
	        e.printStackTrace();
	      }
		driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).sendKeys("ual2@ual.es");
		// 6 | type | css=.form-group:nth-child(2) > .form-control | user123
		driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("ual123");
		// 7 | click | css=.button-text |
		driver.findElement(By.cssSelector(".button-text")).click();
		// 8 | click | id=header-account-menu-link |
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Account Settings")));
		}
		try {
	        Thread.sleep(1000);
	      } catch (InterruptedException e) {
	        e.printStackTrace();
	      }
		// 9 | click | linkText=Settings |
		driver.findElement(By.linkText("Account Settings")).click();
		// 10 | click | linkText=Edit profile |
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Edit profile")));
		}
		try {
	        Thread.sleep(1000);
	      } catch (InterruptedException e) {
	        e.printStackTrace();
	      }
		driver.findElement(By.linkText("Edit profile")).click();
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.elementToBeClickable(By.id("full-name")));
		}
		try {
	        Thread.sleep(1000);
	      } catch (InterruptedException e) {
	        e.printStackTrace();
	      }
		// 11 | type | id=full-name | user1234
		driver.findElement(By.id("full-name")).sendKeys(Keys.chord(Keys.CONTROL, "a"));
		driver.findElement(By.id("full-name")).sendKeys(Keys.chord(Keys.DELETE));
		driver.findElement(By.id("full-name")).sendKeys("ual22");
		// 12 | click | css=.button-text |
		//driver.findElement(By.cssSelector(".button-text")).click();
		// 13 | click | linkText=Edit profile |
		// 14 | click | id=email-address |
		//driver.findElement(By.id("email-address")).click();
		// 15 | type | id=email-address | user12@ual.es
		driver.findElement(By.id("email-address")).sendKeys(Keys.chord(Keys.CONTROL, "a"));
		driver.findElement(By.id("email-address")).sendKeys(Keys.chord(Keys.DELETE));

		driver.findElement(By.id("email-address")).sendKeys("ual22@ual.es");
		// 16 | click | css=.button-text |
		driver.findElement(By.cssSelector(".button-text")).click();
		
		// 17 | click | linkText=Change password |
		
		// 39 | mouseOut | css=.ajax-button |
		// 40 | click | id=header-account-menu-link |
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Sign out")));
		}
		try {
	        Thread.sleep(1000);
	      } catch (InterruptedException e) {
	        e.printStackTrace();
	      }
		driver.findElement(By.linkText("Sign out")).click();
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Log in")));
		}
		try {
	        Thread.sleep(1000);
	      } catch (InterruptedException e) {
	        e.printStackTrace();
	      }
		driver.findElement(By.linkText("Log in")).click();
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".form-group:nth-child(1) > .form-control")));
		}
		try {
	        Thread.sleep(1000);
	      } catch (InterruptedException e) {
	        e.printStackTrace();
	      }
		// 4 | click | css=.form-group:nth-child(1) > .form-control |
		//driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
		// 5 | type | css=.form-group:nth-child(1) > .form-control | user1@ual.es
		driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).sendKeys("ual22@ual.es");
		// 6 | type | css=.form-group:nth-child(2) > .form-control | user123
		driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("ual123");
		// 7 | click | css=.button-text |
		driver.findElement(By.cssSelector(".button-text")).click();
		// 8 | click | id=header-account-menu-link |
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Account Settings")));
		}
		try {
	        Thread.sleep(1000);
	      } catch (InterruptedException e) {
	        e.printStackTrace();
	      }
		// 9 | click | linkText=Settings |
		driver.findElement(By.linkText("Account Settings")).click();
		// 10 | click | linkText=Edit profile |
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Edit profile")));
		}
		try {
	        Thread.sleep(1000);
	      } catch (InterruptedException e) {
	        e.printStackTrace();
	      }
		driver.findElement(By.linkText("Edit profile")).click();
		// 11 | type | id=full-name | user1234
		driver.findElement(By.id("full-name")).sendKeys(Keys.chord(Keys.CONTROL, "a"));
		driver.findElement(By.id("full-name")).sendKeys(Keys.chord(Keys.DELETE));
		driver.findElement(By.id("full-name")).sendKeys("ual2");
		// 14 | click | id=email-address |
		driver.findElement(By.id("email-address")).click();
		// 15 | type | id=email-address | user12@ual.es
		driver.findElement(By.id("email-address")).sendKeys(Keys.chord(Keys.CONTROL, "a"));
		driver.findElement(By.id("email-address")).sendKeys(Keys.chord(Keys.DELETE));

		driver.findElement(By.id("email-address")).sendKeys("ual2@ual.es");
		// 16 | click | css=.button-text |
		System.out.println("W4");
		driver.findElement(By.cssSelector(".button-text")).click();
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Sign out")));
		}
		try {
	        Thread.sleep(1000);
	      } catch (InterruptedException e) {
	        e.printStackTrace();
	      }
		driver.findElement(By.linkText("Sign out")).click();
	}
}
