// Generated by Selenium IDE
package org.ual.cnsa.agu528;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class EditarelusuariologueadoCITest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void editarelusuariologueadoCI() {
    // Test name: Editar el usuario logueado(CI)
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://webapps.alejandrogacles.tech:8080//");
    // 2 | setWindowSize | 1009x728 | 
    driver.manage().window().setSize(new Dimension(1009, 728));
    // 3 | click | linkText=Log in | 
    driver.findElement(By.linkText("Log in")).click();
    // 4 | type | css=.form-group:nth-child(1) > .form-control | user1@ual.es
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).sendKeys("user1@ual.es");
    // 5 | type | css=.form-group:nth-child(2) > .form-control | user123
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("user123");
    // 6 | click | css=.button-text | 
    driver.findElement(By.cssSelector(".button-text")).click();
    // 7 | mouseOver | css=.button-text | 
    {
      WebElement element = driver.findElement(By.cssSelector(".button-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 8 | mouseOut | css=.button-loader | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 9 | click | id=header-account-menu-link | 
    driver.findElement(By.id("header-account-menu-link")).click();
    // 10 | click | linkText=Settings | 
    driver.findElement(By.linkText("Settings")).click();
    // 11 | click | linkText=Edit profile | 
    driver.findElement(By.linkText("Edit profile")).click();
    // 12 | click | css=.row:nth-child(1) > .col-sm-6:nth-child(1) | 
    driver.findElement(By.cssSelector(".row:nth-child(1) > .col-sm-6:nth-child(1)")).click();
    // 13 | click | css=.button-text | 
    driver.findElement(By.cssSelector(".button-text")).click();
    // 14 | mouseOver | css=.button-text | 
    {
      WebElement element = driver.findElement(By.cssSelector(".button-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 15 | mouseOut | css=.button-text | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 16 | click | css=.row:nth-child(1) > .col-sm-6:nth-child(1) | 
    driver.findElement(By.cssSelector(".row:nth-child(1) > .col-sm-6:nth-child(1)")).click();
    // 17 | assertText | css=.invalid-feedback | Please enter your full name.
    assertThat(driver.findElement(By.cssSelector(".invalid-feedback")).getText(), is("Please enter your full name."));
    // 18 | click | css=.row:nth-child(1) > .col-sm-6:nth-child(2) | 
    driver.findElement(By.cssSelector(".row:nth-child(1) > .col-sm-6:nth-child(2)")).click();
    // 19 | click | css=.button-text | 
    driver.findElement(By.cssSelector(".button-text")).click();
    // 20 | mouseOver | css=.button-text | 
    {
      WebElement element = driver.findElement(By.cssSelector(".button-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 21 | mouseOut | css=.button-text | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 22 | click | css=.row:nth-child(1) > .col-sm-6:nth-child(2) | 
    driver.findElement(By.cssSelector(".row:nth-child(1) > .col-sm-6:nth-child(2)")).click();
    // 23 | assertText | css=.col-sm-6:nth-child(2) .invalid-feedback | Please enter a valid email address.
    assertThat(driver.findElement(By.cssSelector(".col-sm-6:nth-child(2) .invalid-feedback")).getText(), is("Please enter a valid email address."));
    // 24 | click | linkText=Cancel | 
    driver.findElement(By.linkText("Cancel")).click();
    // 25 | click | linkText=Change password | 
    driver.findElement(By.linkText("Change password")).click();
    // 26 | click | css=.ajax-button | 
    driver.findElement(By.cssSelector(".ajax-button")).click();
    // 27 | click | css=.row:nth-child(1) > .col-sm-6:nth-child(1) | 
    driver.findElement(By.cssSelector(".row:nth-child(1) > .col-sm-6:nth-child(1)")).click();
    // 28 | assertText | css=.col-sm-6:nth-child(1) .invalid-feedback | Please enter a password or choose "Cancel".
    assertThat(driver.findElement(By.cssSelector(".col-sm-6:nth-child(1) .invalid-feedback")).getText(), is("Please enter a password or choose \\\"Cancel\\\"."));
    // 29 | click | css=.col-sm-6:nth-child(2) .invalid-feedback | 
    driver.findElement(By.cssSelector(".col-sm-6:nth-child(2) .invalid-feedback")).click();
    // 30 | assertText | css=.col-sm-6:nth-child(2) .invalid-feedback | Your new password and confirmation do not match.
    assertThat(driver.findElement(By.cssSelector(".col-sm-6:nth-child(2) .invalid-feedback")).getText(), is("Your new password and confirmation do not match."));
    // 31 | click | linkText=Cancel | 
    driver.findElement(By.linkText("Cancel")).click();
    // 32 | click | id=header-account-menu-link | 
    driver.findElement(By.id("header-account-menu-link")).click();
    // 33 | click | linkText=Sign out | 
    driver.findElement(By.linkText("Sign out")).click();
  }
}
