// Generated by Selenium IDE
package org.ual.cnsa.agu528;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LogindeusuarioCCTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void logindeusuarioCC() {
    // Test name: Login de usuario(CC)
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://webapps.alejandrogacles.tech:8080//");
    // 2 | setWindowSize | 813x728 | 
    driver.manage().window().setSize(new Dimension(813, 728));
    // 3 | click | linkText=Sign up | 
    driver.findElement(By.linkText("Sign up")).click();
    // 4 | click | id=full-name | 
    driver.findElement(By.id("full-name")).click();
    // 5 | executeScript | return "ual-" + Math.floor(Math.random()*1500000) | namerandom
    vars.put("namerandom", js.executeScript("return \"ual-\" + Math.floor(Math.random()*1500000)"));
    // 6 | type | id=full-name | ${namerandom}
    driver.findElement(By.id("full-name")).sendKeys(vars.get("namerandom").toString());
    // 7 | executeScript | return "ual-" + Math.floor(Math.random()*1500000)+"@ual.es" | emailrandom
    vars.put("emailrandom", js.executeScript("return \"ual-\" + Math.floor(Math.random()*1500000)+\"@ual.es\""));
    // 8 | type | id=email-address | ${emailrandom}
    driver.findElement(By.id("email-address")).sendKeys(vars.get("emailrandom").toString());
    // 9 | type | id=password | password123
    driver.findElement(By.id("password")).sendKeys("password123");
    // 10 | type | id=confirm-password | password123
    driver.findElement(By.id("confirm-password")).sendKeys("password123");
    // 11 | click | id=terms-agreement | 
    driver.findElement(By.id("terms-agreement")).click();
    // 12 | click | css=.ajax-button | 
    driver.findElement(By.cssSelector(".ajax-button")).click();
    // 13 | click | id=header-account-menu-link | 
    driver.findElement(By.id("header-account-menu-link")).click();
    // 14 | click | linkText=Sign out | 
    driver.findElement(By.linkText("Sign out")).click();
    // 15 | click | linkText=Log in | 
    driver.findElement(By.linkText("Log in")).click();
    // 16 | click | css=.form-group:nth-child(1) > .form-control | 
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
    // 17 | type | css=.form-group:nth-child(1) > .form-control | ${emailrandom}
    driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).sendKeys(vars.get("emailrandom").toString());
    // 18 | type | css=.form-group:nth-child(2) > .form-control | password123
    driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("password123");
    // 19 | click | css=.ajax-button | 
    driver.findElement(By.cssSelector(".ajax-button")).click();
    // 20 | click | id=header-account-menu-link | 
    driver.findElement(By.id("header-account-menu-link")).click();
    // 21 | click | linkText=Sign out | 
    driver.findElement(By.linkText("Sign out")).click();
  }
}
